# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Diymenu.delete_all
Diymenu.create(id: 1, name: '预报服务', is_show: true, sort: 0)
Diymenu.create(id: 2, name: '我的社区', is_show: true, sort: 1)
Diymenu.create(id: 3, name: '其他', is_show: true, sort:2)
Diymenu.create(id: 4, parent_id: 1, name: '全市预警', key: '全市预警', is_show: true, sort:0)
Diymenu.create(id: 5, parent_id: 1, name: '五日预报', key: '五日预报', is_show: true, sort:1)
Diymenu.create(id: 6, parent_id: 1, name: '气象指数', key: '气象指数', is_show: true, sort:2)
Diymenu.create(id: 7, parent_id: 1, name: '空气质量', key: '空气质量', is_show: true, sort:3)
Diymenu.create(id: 8, parent_id: 1, name: '健康气象', key: '健康气象', is_show: true, sort:4)
Diymenu.create(id: 9, parent_id: 2, name: '社区预警', key: '社区预警', is_show: true, sort:0)
Diymenu.create(id: 10, parent_id: 2, name: '灾情互动', key: '灾情互动', is_show: true, sort:1)
Diymenu.create(id: 11, parent_id: 2, name: '实况监测', key: '实况监测', is_show: true, sort:2)
Diymenu.create(id: 12, parent_id: 2, name: '社区风险', key: '社区风险', is_show: true, sort:3)
Diymenu.create(id: 13, parent_id: 3, name: '调查问卷', key: '调查问卷', is_show: true, sort:0)
Diymenu.create(id: 14, parent_id: 3, name: '气象科普', key: '气象科普', is_show: true, sort:1)
Diymenu.create(id: 15, parent_id: 3, name: '微社区', url: 'http://wsq.qq.com/reflow/234704148', is_show: true, sort:2)
Diymenu.create(id: 16, parent_id: 3, name: '帮助', key: '帮助', is_show: true, sort:3)

MessageProcessor.delete_all
# MessageProcessor.create(event_key: "全市预警", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "五日预报", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "气象指数", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "空气质量", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "健康气象", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "社区预警", process_class_name: "", process_method: "", result_type: "")
MessageProcessor.create(event_key: "灾情互动", process_class_name: "article", process_method: "get_show_article", result_type: "news_message")
# MessageProcessor.create(event_key: "实况监测", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "社区风险", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "调查问卷", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "气象科普", process_class_name: "", process_method: "", result_type: "")
# MessageProcessor.create(event_key: "帮助", process_class_name: "", process_method: "", result_type: "")

Community.delete_all
Community.create(street: "杨浦", district: "五角场街道", c_type: "普通")
Community.create(street: "杨浦", district: "新江湾街道", c_type: "普通")
Community.create(street: "杨浦", district: "江浦路街道", c_type: "普通")
Community.create(street: "杨浦", district: "四平路街道", c_type: "普通")
Community.create(street: "杨浦", district: "五角场镇", c_type: "普通")
Community.create(street: "杨浦", district: "延吉新村街道", c_type: "普通")
Community.create(street: "杨浦", district: "殷行街道", c_type: "普通")
Community.create(street: "杨浦", district: "定海路街道", c_type: "普通")
Community.create(street: "杨浦", district: "大桥街道", c_type: "普通")
Community.create(street: "杨浦", district: "平凉路街道", c_type: "普通")
Community.create(street: "杨浦", district: "长白新村街道", c_type: "普通")
Community.create(street: "杨浦", district: "控江路街道", c_type: "普通")
Community.create(street: "黄浦", district: "南京东路街道", c_type: "普通")
Community.create(street: "黄浦", district: "外滩街道", c_type: "普通")
Community.create(street: "黄浦", district: "老西门街道", c_type: "普通")
Community.create(street: "黄浦", district: "半淞园街道", c_type: "普通")
Community.create(street: "黄浦", district: "小东门街道", c_type: "普通")
Community.create(street: "黄浦", district: "豫园街道", c_type: "普通")
Community.create(street: "黄浦", district: "打浦桥街道", c_type: "普通")
Community.create(street: "黄浦", district: "淮海中路街道", c_type: "普通")
Community.create(street: "黄浦", district: "瑞金二路街道", c_type: "普通")
Community.create(street: "黄浦", district: "五里桥街道", c_type: "普通")
Community.create(street: "徐汇", district: "天平路街道", c_type: "普通")
Community.create(street: "徐汇", district: "湖南路街道", c_type: "普通")
Community.create(street: "徐汇", district: "斜土路街道", c_type: "普通")
Community.create(street: "徐汇", district: "枫林路街道", c_type: "普通")
Community.create(street: "徐汇", district: "长桥街道", c_type: "普通")
Community.create(street: "徐汇", district: "田林街道", c_type: "普通")
Community.create(street: "徐汇", district: "虹梅路街道", c_type: "普通")
Community.create(street: "徐汇", district: "康健新村街道", c_type: "普通")
Community.create(street: "徐汇", district: "徐家汇路街道", c_type: "普通")
Community.create(street: "徐汇", district: "龙华街道", c_type: "普通")
Community.create(street: "徐汇", district: "漕河泾街道", c_type: "普通")
Community.create(street: "徐汇", district: "华泾镇", c_type: "普通")
Community.create(street: "徐汇", district: "凌云路街道", c_type: "普通")
Community.create(street: "长宁", district: "华阳路街道", c_type: "普通")
Community.create(street: "长宁", district: "江苏路街道", c_type: "普通")
Community.create(street: "长宁", district: "天山路街道", c_type: "普通")
Community.create(street: "长宁", district: "周家桥街道", c_type: "普通")
Community.create(street: "长宁", district: "新华路街道", c_type: "普通")
Community.create(street: "长宁", district: "仙霞新村街道", c_type: "普通")
Community.create(street: "长宁", district: "虹桥街道", c_type: "普通")
Community.create(street: "长宁", district: "程家桥街道", c_type: "普通")
Community.create(street: "长宁", district: "北新泾街道", c_type: "普通")
Community.create(street: "长宁", district: "新泾镇", c_type: "普通")
Community.create(street: "静安", district: "曹家渡街道", c_type: "普通")
Community.create(street: "静安", district: "江宁路街道", c_type: "普通")
Community.create(street: "静安", district: "静安寺街道", c_type: "普通")
Community.create(street: "静安", district: "南京西路街道", c_type: "普通")
Community.create(street: "静安", district: "石门二路街道", c_type: "普通")
Community.create(street: "普陀", district: "长寿路街道", c_type: "普通")
Community.create(street: "普陀", district: "石泉路街道", c_type: "普通")
Community.create(street: "普陀", district: "曹杨新村街道", c_type: "普通")
Community.create(street: "普陀", district: "长风新村街道", c_type: "普通")
Community.create(street: "普陀", district: "宜川路街道", c_type: "普通")
Community.create(street: "普陀", district: "甘泉路街道", c_type: "普通")
Community.create(street: "普陀", district: "桃浦镇", c_type: "普通")
Community.create(street: "普陀", district: "长征镇", c_type: "普通")
Community.create(street: "普陀", district: "真如镇", c_type: "普通")
Community.create(street: "闸北", district: "北站街道", c_type: "普通")
Community.create(street: "闸北", district: "临汾路街道", c_type: "普通")
Community.create(street: "闸北", district: "彭浦新村街道", c_type: "普通")
Community.create(street: "闸北", district: "天目西路街道", c_type: "普通")
Community.create(street: "闸北", district: "宝山路街道", c_type: "普通")
Community.create(street: "闸北", district: "芷江西路街道", c_type: "普通")
Community.create(street: "闸北", district: "共和新路街道", c_type: "普通")
Community.create(street: "闸北", district: "大宁路街道", c_type: "普通")
Community.create(street: "闸北", district: "彭浦镇", c_type: "普通")
Community.create(street: "虹口", district: "曲阳路街道", c_type: "普通")
Community.create(street: "虹口", district: "欧阳路街道", c_type: "普通")
Community.create(street: "虹口", district: "提篮桥街道", c_type: "普通")
Community.create(street: "虹口", district: "嘉兴路街道", c_type: "普通")
Community.create(street: "虹口", district: "广中路街道", c_type: "普通")
Community.create(street: "虹口", district: "江湾镇街道", c_type: "普通")
Community.create(street: "虹口", district: "凉城新村街道", c_type: "普通")
Community.create(street: "虹口", district: "四川北路街道", c_type: "普通")
Community.create(street: "闵行", district: "江川路街道", c_type: "普通")
Community.create(street: "闵行", district: "古美路街道", c_type: "普通")
Community.create(street: "闵行", district: "吴泾镇", c_type: "普通")
Community.create(street: "闵行", district: "梅陇镇", c_type: "普通")
Community.create(street: "闵行", district: "莘庄镇", c_type: "普通")
Community.create(street: "闵行", district: "华漕镇", c_type: "普通")
Community.create(street: "闵行", district: "虹桥镇", c_type: "普通")
Community.create(street: "闵行", district: "七宝镇", c_type: "普通")
Community.create(street: "闵行", district: "颛桥镇", c_type: "普通")
Community.create(street: "闵行", district: "新虹街道", c_type: "普通")
Community.create(street: "闵行", district: "莘庄工业区", c_type: "普通")
Community.create(street: "闵行", district: "马桥镇", c_type: "普通")
Community.create(street: "闵行", district: "浦江镇", c_type: "普通")
Community.create(street: "宝山", district: "吴淞街道", c_type: "普通")
Community.create(street: "宝山", district: "张庙街道", c_type: "普通")
Community.create(street: "宝山", district: "友谊路街道", c_type: "普通")
Community.create(street: "宝山", district: "月浦镇", c_type: "普通")
Community.create(street: "宝山", district: "大场镇", c_type: "普通")
Community.create(street: "宝山", district: "罗店镇", c_type: "普通")
Community.create(street: "宝山", district: "杨行镇", c_type: "普通")
Community.create(street: "宝山", district: "罗泾镇", c_type: "普通")
Community.create(street: "宝山", district: "顾村镇", c_type: "普通")
Community.create(street: "宝山", district: "高境镇", c_type: "普通")
Community.create(street: "宝山", district: "庙行镇", c_type: "普通")
Community.create(street: "宝山", district: "淞南镇", c_type: "普通")
Community.create(street: "嘉定", district: "嘉定工业区", c_type: "普通")
Community.create(street: "嘉定", district: "嘉定镇", c_type: "普通")
Community.create(street: "嘉定", district: "江桥镇", c_type: "普通")
Community.create(street: "嘉定", district: "安亭镇", c_type: "普通")
Community.create(street: "嘉定", district: "真新街道", c_type: "普通")
Community.create(street: "嘉定", district: "外冈镇", c_type: "普通")
Community.create(street: "嘉定", district: "华亭镇", c_type: "普通")
Community.create(street: "嘉定", district: "徐行镇", c_type: "普通")
Community.create(street: "嘉定", district: "黄渡镇", c_type: "普通")
Community.create(street: "嘉定", district: "菊园新区", c_type: "普通")
Community.create(street: "嘉定", district: "马陆镇", c_type: "普通")
Community.create(street: "嘉定", district: "南翔镇", c_type: "普通")
Community.create(street: "嘉定", district: "新城路街道", c_type: "普通")
Community.create(street: "浦东新区", district: "沪东新村街道", c_type: "普通")
Community.create(street: "浦东新区", district: "金杨新村街道", c_type: "普通")
Community.create(street: "浦东新区", district: "陆家嘴街道", c_type: "普通")
Community.create(street: "浦东新区", district: "南码头街道", c_type: "普通")
Community.create(street: "浦东新区", district: "上钢新村街道", c_type: "普通")
Community.create(street: "浦东新区", district: "塘桥街道", c_type: "普通")
Community.create(street: "浦东新区", district: "潍坊新村街道", c_type: "普通")
Community.create(street: "浦东新区", district: "洋泾街道", c_type: "普通")
Community.create(street: "浦东新区", district: "周家渡街道", c_type: "普通")
Community.create(street: "浦东新区", district: "浦兴路街道", c_type: "普通")
Community.create(street: "浦东新区", district: "东明街道", c_type: "普通")
Community.create(street: "浦东新区", district: "花木街道", c_type: "普通")
Community.create(street: "浦东新区", district: "三林镇", c_type: "普通")
Community.create(street: "浦东新区", district: "川沙新镇", c_type: "普通")
Community.create(street: "浦东新区", district: "高桥镇", c_type: "普通")
Community.create(street: "浦东新区", district: "北蔡镇", c_type: "普通")
Community.create(street: "浦东新区", district: "张江镇", c_type: "普通")
Community.create(street: "浦东新区", district: "曹路镇", c_type: "普通")
Community.create(street: "浦东新区", district: "唐镇", c_type: "普通")
Community.create(street: "浦东新区", district: "合庆镇", c_type: "普通")
Community.create(street: "浦东新区", district: "金桥镇", c_type: "普通")
Community.create(street: "浦东新区", district: "高东镇", c_type: "普通")
Community.create(street: "浦东新区", district: "高行镇", c_type: "普通")
Community.create(street: "浦东新区", district: "惠南镇", c_type: "普通")
Community.create(street: "浦东新区", district: "周浦镇", c_type: "普通")
Community.create(street: "浦东新区", district: "新场镇", c_type: "普通")
Community.create(street: "浦东新区", district: "大团镇", c_type: "普通")
Community.create(street: "浦东新区", district: "芦潮港镇", c_type: "普通")
Community.create(street: "浦东新区", district: "康桥镇", c_type: "普通")
Community.create(street: "浦东新区", district: "航头镇", c_type: "普通")
Community.create(street: "浦东新区", district: "六灶镇", c_type: "普通")
Community.create(street: "浦东新区", district: "祝桥镇", c_type: "普通")
Community.create(street: "浦东新区", district: "泥城镇", c_type: "普通")
Community.create(street: "浦东新区", district: "宣桥镇", c_type: "普通")
Community.create(street: "浦东新区", district: "书院镇", c_type: "普通")
Community.create(street: "浦东新区", district: "万祥镇镇", c_type: "普通")
Community.create(street: "浦东新区", district: "老港镇", c_type: "普通")
Community.create(street: "浦东新区", district: "芦潮港农场", c_type: "普通")
Community.create(street: "浦东新区", district: "东海农场", c_type: "普通")
Community.create(street: "浦东新区", district: "朝阳农场", c_type: "普通")
Community.create(street: "浦东新区", district: "申港街道", c_type: "普通")
Community.create(street: "浦东新区", district: "老港镇", c_type: "普通")
Community.create(street: "金山", district: "石化街道", c_type: "普通")
Community.create(street: "金山", district: "朱泾镇", c_type: "普通")
Community.create(street: "金山", district: "吕巷镇", c_type: "普通")
Community.create(street: "金山", district: "廊下镇", c_type: "普通")
Community.create(street: "金山", district: "金山卫镇", c_type: "普通")
Community.create(street: "金山", district: "枫泾镇", c_type: "普通")
Community.create(street: "金山", district: "漕泾镇", c_type: "普通")
Community.create(street: "金山", district: "山阳镇", c_type: "普通")
Community.create(street: "金山", district: "亭林镇", c_type: "普通")
Community.create(street: "金山", district: "张堰镇", c_type: "普通")
Community.create(street: "金山", district: "金山工业区", c_type: "普通")
Community.create(street: "松江", district: "岳阳街道", c_type: "普通")
Community.create(street: "松江", district: "永丰街道", c_type: "普通")
Community.create(street: "松江", district: "方松街道", c_type: "普通")
Community.create(street: "松江", district: "中山街道", c_type: "普通")
Community.create(street: "松江", district: "泗泾镇", c_type: "普通")
Community.create(street: "松江", district: "佘山镇", c_type: "普通")
Community.create(street: "松江", district: "洞泾镇", c_type: "普通")
Community.create(street: "松江", district: "车墩镇", c_type: "普通")
Community.create(street: "松江", district: "新桥镇", c_type: "普通")
Community.create(street: "松江", district: "九亭镇", c_type: "普通")
Community.create(street: "松江", district: "泖港镇", c_type: "普通")
Community.create(street: "松江", district: "石湖荡镇", c_type: "普通")
Community.create(street: "松江", district: "新浜镇", c_type: "普通")
Community.create(street: "松江", district: "叶榭镇", c_type: "普通")
Community.create(street: "松江", district: "小昆山镇", c_type: "普通")
Community.create(street: "青浦", district: "夏阳街道", c_type: "普通")
Community.create(street: "青浦", district: "盈浦街道", c_type: "普通")
Community.create(street: "青浦", district: "香花桥街道", c_type: "普通")
Community.create(street: "青浦", district: "朱家角街道", c_type: "普通")
Community.create(street: "青浦", district: "练塘镇", c_type: "普通")
Community.create(street: "青浦", district: "金泽镇", c_type: "普通")
Community.create(street: "青浦", district: "赵巷镇", c_type: "普通")
Community.create(street: "青浦", district: "徐泾镇", c_type: "普通")
Community.create(street: "青浦", district: "华新镇", c_type: "普通")
Community.create(street: "青浦", district: "重固镇", c_type: "普通")
Community.create(street: "青浦", district: "白鹤镇", c_type: "普通")
Community.create(street: "奉贤", district: "南桥镇", c_type: "普通")
Community.create(street: "奉贤", district: "奉城镇", c_type: "普通")
Community.create(street: "奉贤", district: "四团镇", c_type: "普通")
Community.create(street: "奉贤", district: "金汇镇", c_type: "普通")
Community.create(street: "奉贤", district: "青村镇", c_type: "普通")
Community.create(street: "奉贤", district: "庄行镇", c_type: "普通")
Community.create(street: "奉贤", district: "柘林镇", c_type: "普通")
Community.create(street: "奉贤", district: "海湾镇", c_type: "普通")
Community.create(street: "崇明", district: "城桥镇", c_type: "普通")
Community.create(street: "崇明", district: "堡镇", c_type: "普通")
Community.create(street: "崇明", district: "新河镇", c_type: "普通")
Community.create(street: "崇明", district: "庙镇", c_type: "普通")
Community.create(street: "崇明", district: "竖新镇", c_type: "普通")
Community.create(street: "崇明", district: "向化镇", c_type: "普通")
Community.create(street: "崇明", district: "三星镇", c_type: "普通")
Community.create(street: "崇明", district: "港沿镇", c_type: "普通")
Community.create(street: "崇明", district: "中兴镇", c_type: "普通")
Community.create(street: "崇明", district: "陈家镇", c_type: "普通")
Community.create(street: "崇明", district: "绿华镇", c_type: "普通")
Community.create(street: "崇明", district: "港西镇", c_type: "普通")
Community.create(street: "崇明", district: "建设镇", c_type: "普通")
Community.create(street: "崇明", district: "新村乡", c_type: "普通")
Community.create(street: "崇明", district: "长兴镇", c_type: "普通")
Community.create(street: "崇明", district: "横沙乡", c_type: "普通")
Community.create(street: "崇明", district: "东平镇", c_type: "普通")
Community.create(street: "崇明", district: "新海镇", c_type: "普通")
