# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Diymenu.delete_all
Diymenu.create(id: 1, name: '预报服务', is_show: true, sort: 0)
Diymenu.create(id: 2, name: '我的社区', is_show: true, sort: 1)
Diymenu.create(id: 3, name: '其他', is_show: true, sort:2)
Diymenu.create(id: 4, parent_id: 1, name: '全市预警', key: '全市预警', is_show: true, sort:0)
Diymenu.create(id: 5, parent_id: 1, name: '五日预报', key: '五日预报', is_show: true, sort:1)
Diymenu.create(id: 6, parent_id: 1, name: '气象指数', key: '气象指数', is_show: true, sort:2)
Diymenu.create(id: 7, parent_id: 1, name: '空气质量', key: '空气质量', is_show: true, sort:3)
Diymenu.create(id: 8, parent_id: 1, name: '健康气象', key: '健康气象', is_show: true, sort:4)
Diymenu.create(id: 9, parent_id: 2, name: '社区预警', key: '社区预警', is_show: true, sort:0)
Diymenu.create(id: 10, parent_id: 2, name: '灾情互动', key: '灾情互动', is_show: true, sort:1)
Diymenu.create(id: 11, parent_id: 2, name: '实况监测', key: '实况监测', is_show: true, sort:2)
Diymenu.create(id: 12, parent_id: 2, name: '社区风险', key: '社区风险', is_show: true, sort:3)
Diymenu.create(id: 13, parent_id: 3, name: '调查问卷', key: '调查问卷', is_show: true, sort:0)
Diymenu.create(id: 14, parent_id: 3, name: '气象科普', key: '气象科普', is_show: true, sort:1)
Diymenu.create(id: 15, parent_id: 3, name: '微社区', url: 'http://wsq.qq.com/reflow/234704148', is_show: true, sort:2)
Diymenu.create(id: 16, parent_id: 3, name: '帮助', key: '帮助', is_show: true, sort:3)

MessageProcessor.delete_all
MessageProcessor.create(event_key: "全市预警", process_class_name: "Warning", process_method: "get_show_article", result_type: "news_message")
MessageProcessor.create(event_key: "五日预报", process_class_name: "FiveDayWeather", process_method: "get_message", result_type: "text_message")
MessageProcessor.create(event_key: "气象指数", process_class_name: "WeatherIndex", process_method: "get_message", result_type: "text_message")
MessageProcessor.create(event_key: "空气质量", process_class_name: "AQI", process_method: "get_show_article", result_type: "news_message")
MessageProcessor.create(event_key: "健康气象", process_class_name: "Healthy", process_method: "get_message", result_type: "text_message")
MessageProcessor.create(event_key: "社区预警", process_class_name: "CommWarning", process_method: "get_show_article", result_type: "news_message")
MessageProcessor.create(event_key: "灾情互动", message_type: "dynamic", process_class_name: "Article", process_method: "get_show_article", result_type: "news_message")
MessageProcessor.create(event_key: "实况监测", process_class_name: "MonitorStation", process_method: "get_show_article", result_type: "news_message")
MessageProcessor.create(event_key: "社区风险", message_type: "dynamic", message_type: "dynamic", message_type: "dynamic", process_class_name: "Article", process_method: "get_show_article", result_type: "news_message")
MessageProcessor.create(event_key: "调查问卷", process_class_name: "Article", process_method: "get_show_article", result_type: "news_message")
MessageProcessor.create(event_key: "气象科普", message_type: "dynamic", message_type: "dynamic", process_class_name: "Article", process_method: "get_show_article", result_type: "news_message")
MessageProcessor.create(event_key: "帮助", message_type: "dynamic", process_class_name: "Article", process_method: "get_show_article", result_type: "news_message")

Article.create(title: "社区绑定", author: "系统", content: "abc", thumb_media_url: "assets/community2.png")
Article.create(title: "灾情互动", author: "系统", content: "abc", digest: "您想及时与大家分享您身边的气象灾情吗?可加入社区气象志愿者队伍,上传灾情照片与描述,就可以为社区气象安全尽一份力哦~", thumb_media_url: "assets/community2.png")

Community.delete_all
Community.create(id: 1, code: 20000, street: "上海", district: "上海", c_type: "普通")
Community.create(id: 2, code: 20100, street: "杨浦", district: "五角场街道", c_type: "普通")
Community.create(id: 3, code: 20101, street: "杨浦", district: "新江湾街道", c_type: "普通")
Community.create(id: 4, code: 20102, street: "杨浦", district: "江浦路街道", c_type: "普通")
Community.create(id: 5, code: 20103, street: "杨浦", district: "四平路街道", c_type: "普通")
Community.create(id: 6, code: 20104, street: "杨浦", district: "五角场镇", c_type: "普通")
Community.create(id: 7, code: 20105, street: "杨浦", district: "延吉新村街道", c_type: "普通")
Community.create(id: 8, code: 20106, street: "杨浦", district: "殷行街道", c_type: "普通")
Community.create(id: 9, code: 20107, street: "杨浦", district: "定海路街道", c_type: "普通")
Community.create(id: 10, code: 20108, street: "杨浦", district: "大桥街道", c_type: "普通")
Community.create(id: 11, code: 20109, street: "杨浦", district: "平凉路街道", c_type: "普通")
Community.create(id: 12, code: 20110, street: "杨浦", district: "长白新村街道", c_type: "普通")
Community.create(id: 13, code: 20111, street: "杨浦", district: "控江路街道", c_type: "普通")
Community.create(id: 14, code: 20200, street: "黄浦", district: "南京东路街道", c_type: "普通")
Community.create(id: 15, code: 20201, street: "黄浦", district: "外滩街道", c_type: "普通")
Community.create(id: 16, code: 20203, street: "黄浦", district: "老西门街道", c_type: "普通")
Community.create(id: 17, code: 20204, street: "黄浦", district: "半淞园街道", c_type: "普通")
Community.create(id: 18, code: 20205, street: "黄浦", district: "小东门街道", c_type: "普通")
Community.create(id: 19, code: 20206, street: "黄浦", district: "豫园街道", c_type: "普通")
Community.create(id: 20, code: 20207, street: "黄浦", district: "打浦桥街道", c_type: "普通")
Community.create(id: 21, code: 20208, street: "黄浦", district: "淮海中路街道", c_type: "普通")
Community.create(id: 22, code: 20209, street: "黄浦", district: "瑞金二路街道", c_type: "普通")
Community.create(id: 23, code: 20210, street: "黄浦", district: "五里桥街道", c_type: "普通")
Community.create(id: 24, code: 20300, street: "徐汇", district: "天平路街道", c_type: "普通")
Community.create(id: 25, code: 20301, street: "徐汇", district: "湖南路街道", c_type: "普通")
Community.create(id: 26, code: 20302, street: "徐汇", district: "斜土路街道", c_type: "普通")
Community.create(id: 27, code: 20303, street: "徐汇", district: "枫林路街道", c_type: "普通")
Community.create(id: 28, code: 20304, street: "徐汇", district: "长桥街道", c_type: "普通")
Community.create(id: 29, code: 20305, street: "徐汇", district: "田林街道", c_type: "普通")
Community.create(id: 30, code: 20306, street: "徐汇", district: "虹梅路街道", c_type: "普通")
Community.create(id: 31, code: 20307, street: "徐汇", district: "康健新村街道", c_type: "普通")
Community.create(id: 32, code: 20308, street: "徐汇", district: "徐家汇路街道", c_type: "普通")
Community.create(id: 33, code: 20309, street: "徐汇", district: "龙华街道", c_type: "普通")
Community.create(id: 34, code: 20310, street: "徐汇", district: "漕河泾街道", c_type: "普通")
Community.create(id: 35, code: 20311, street: "徐汇", district: "华泾镇", c_type: "普通")
Community.create(id: 36, code: 20312, street: "徐汇", district: "凌云路街道", c_type: "普通")
Community.create(id: 37, code: 20400, street: "长宁", district: "华阳路街道", c_type: "普通")
Community.create(id: 38, code: 20401, street: "长宁", district: "江苏路街道", c_type: "普通")
Community.create(id: 39, code: 20402, street: "长宁", district: "天山路街道", c_type: "普通")
Community.create(id: 40, code: 20403, street: "长宁", district: "周家桥街道", c_type: "普通")
Community.create(id: 41, code: 20404, street: "长宁", district: "新华路街道", c_type: "普通")
Community.create(id: 42, code: 20405, street: "长宁", district: "仙霞新村街道", c_type: "普通")
Community.create(id: 43, code: 20406, street: "长宁", district: "虹桥街道", c_type: "普通")
Community.create(id: 44, code: 20407, street: "长宁", district: "程家桥街道", c_type: "普通")
Community.create(id: 45, code: 20408, street: "长宁", district: "北新泾街道", c_type: "普通")
Community.create(id: 46, code: 20409, street: "长宁", district: "新泾镇", c_type: "普通")
Community.create(id: 47, code: 20500, street: "静安", district: "曹家渡街道", c_type: "普通")
Community.create(id: 48, code: 20501, street: "静安", district: "江宁路街道", c_type: "普通")
Community.create(id: 49, code: 20502, street: "静安", district: "静安寺街道", c_type: "普通")
Community.create(id: 50, code: 20503, street: "静安", district: "南京西路街道", c_type: "普通")
Community.create(id: 51, code: 20504, street: "静安", district: "石门二路街道", c_type: "普通")
Community.create(id: 52, code: 20600, street: "普陀", district: "长寿路街道", c_type: "普通")
Community.create(id: 53, code: 20601, street: "普陀", district: "石泉路街道", c_type: "普通")
Community.create(id: 54, code: 20602, street: "普陀", district: "曹杨新村街道", c_type: "普通")
Community.create(id: 55, code: 20603, street: "普陀", district: "长风新村街道", c_type: "普通")
Community.create(id: 56, code: 20604, street: "普陀", district: "宜川路街道", c_type: "普通")
Community.create(id: 57, code: 20605, street: "普陀", district: "甘泉路街道", c_type: "普通")
Community.create(id: 58, code: 20606, street: "普陀", district: "桃浦镇", c_type: "普通")
Community.create(id: 59, code: 20607, street: "普陀", district: "长征镇", c_type: "普通")
Community.create(id: 60, code: 20608, street: "普陀", district: "真如镇", c_type: "普通")
Community.create(id: 61, code: 20700, street: "闸北", district: "北站街道", c_type: "普通")
Community.create(id: 62, code: 20701, street: "闸北", district: "临汾路街道", c_type: "普通")
Community.create(id: 63, code: 20702, street: "闸北", district: "彭浦新村街道", c_type: "普通")
Community.create(id: 64, code: 20703, street: "闸北", district: "天目西路街道", c_type: "普通")
Community.create(id: 65, code: 20704, street: "闸北", district: "宝山路街道", c_type: "普通")
Community.create(id: 66, code: 20705, street: "闸北", district: "芷江西路街道", c_type: "普通")
Community.create(id: 67, code: 20706, street: "闸北", district: "共和新路街道", c_type: "普通")
Community.create(id: 68, code: 20707, street: "闸北", district: "大宁路街道", c_type: "普通")
Community.create(id: 69, code: 20708, street: "闸北", district: "彭浦镇", c_type: "普通")
Community.create(id: 70, code: 20800, street: "虹口", district: "曲阳路街道", c_type: "普通")
Community.create(id: 71, code: 20801, street: "虹口", district: "欧阳路街道", c_type: "普通")
Community.create(id: 72, code: 20802, street: "虹口", district: "提篮桥街道", c_type: "普通")
Community.create(id: 73, code: 20803, street: "虹口", district: "嘉兴路街道", c_type: "普通")
Community.create(id: 74, code: 20804, street: "虹口", district: "广中路街道", c_type: "普通")
Community.create(id: 75, code: 20805, street: "虹口", district: "江湾镇街道", c_type: "普通")
Community.create(id: 76, code: 20806, street: "虹口", district: "凉城新村街道", c_type: "普通")
Community.create(id: 77, code: 20807, street: "虹口", district: "四川北路街道", c_type: "普通")
Community.create(id: 78, code: 20900, street: "闵行", district: "江川路街道", c_type: "普通")
Community.create(id: 79, code: 20901, street: "闵行", district: "古美路街道", c_type: "普通")
Community.create(id: 80, code: 20902, street: "闵行", district: "吴泾镇", c_type: "普通")
Community.create(id: 81, code: 20903, street: "闵行", district: "梅陇镇", c_type: "普通")
Community.create(id: 82, code: 20904, street: "闵行", district: "莘庄镇", c_type: "普通")
Community.create(id: 83, code: 20905, street: "闵行", district: "华漕镇", c_type: "普通")
Community.create(id: 84, code: 20906, street: "闵行", district: "虹桥镇", c_type: "普通")
Community.create(id: 85, code: 20907, street: "闵行", district: "七宝镇", c_type: "普通")
Community.create(id: 86, code: 20908, street: "闵行", district: "颛桥镇", c_type: "普通")
Community.create(id: 87, code: 20909, street: "闵行", district: "新虹街道", c_type: "普通")
Community.create(id: 88, code: 20910, street: "闵行", district: "莘庄工业区", c_type: "普通")
Community.create(id: 89, code: 20911, street: "闵行", district: "马桥镇", c_type: "普通")
Community.create(id: 90, code: 20912, street: "闵行", district: "浦江镇", c_type: "普通")
Community.create(id: 91, code: 21000, street: "宝山", district: "吴淞街道", c_type: "普通")
Community.create(id: 92, code: 21001, street: "宝山", district: "张庙街道", c_type: "普通")
Community.create(id: 93, code: 21002, street: "宝山", district: "友谊路街道", c_type: "普通")
Community.create(id: 94, code: 21003, street: "宝山", district: "月浦镇", c_type: "普通")
Community.create(id: 95, code: 21004, street: "宝山", district: "大场镇", c_type: "普通")
Community.create(id: 96, code: 21005, street: "宝山", district: "罗店镇", c_type: "普通")
Community.create(id: 97, code: 21006, street: "宝山", district: "杨行镇", c_type: "普通")
Community.create(id: 98, code: 21007, street: "宝山", district: "罗泾镇", c_type: "普通")
Community.create(id: 99, code: 21008, street: "宝山", district: "顾村镇", c_type: "普通")
Community.create(id: 100, code: 21009, street: "宝山", district: "高境镇", c_type: "普通")
Community.create(id: 101, code: 21010, street: "宝山", district: "庙行镇", c_type: "普通")
Community.create(id: 102, code: 21011, street: "宝山", district: "淞南镇", c_type: "普通")
Community.create(id: 103, code: 21100, street: "嘉定", district: "嘉定工业区", c_type: "普通")
Community.create(id: 104, code: 21101, street: "嘉定", district: "嘉定镇", c_type: "普通")
Community.create(id: 105, code: 21102, street: "嘉定", district: "江桥镇", c_type: "普通")
Community.create(id: 106, code: 21103, street: "嘉定", district: "安亭镇", c_type: "普通")
Community.create(id: 107, code: 21104, street: "嘉定", district: "真新街道", c_type: "普通")
Community.create(id: 108, code: 21105, street: "嘉定", district: "外冈镇", c_type: "普通")
Community.create(id: 109, code: 21106, street: "嘉定", district: "华亭镇", c_type: "普通")
Community.create(id: 110, code: 21107, street: "嘉定", district: "徐行镇", c_type: "普通")
Community.create(id: 111, code: 21108, street: "嘉定", district: "黄渡镇", c_type: "普通")
Community.create(id: 112, code: 21109, street: "嘉定", district: "菊园新区", c_type: "普通")
Community.create(id: 113, code: 21110, street: "嘉定", district: "马陆镇", c_type: "普通")
Community.create(id: 114, code: 21111, street: "嘉定", district: "南翔镇", c_type: "普通")
Community.create(id: 115, code: 21112, street: "嘉定", district: "新城路街道", c_type: "普通")
Community.create(id: 116, code: 21200, street: "浦东新区", district: "沪东新村街道", c_type: "普通")
Community.create(id: 117, code: 21201, street: "浦东新区", district: "金杨新村街道", c_type: "普通")
Community.create(id: 118, code: 21202, street: "浦东新区", district: "陆家嘴街道", c_type: "普通")
Community.create(id: 119, code: 21203, street: "浦东新区", district: "南码头街道", c_type: "普通")
Community.create(id: 120, code: 21204, street: "浦东新区", district: "上钢新村街道", c_type: "普通")
Community.create(id: 121, code: 21205, street: "浦东新区", district: "塘桥街道", c_type: "普通")
Community.create(id: 122, code: 21206, street: "浦东新区", district: "潍坊新村街道", c_type: "普通")
Community.create(id: 123, code: 21207, street: "浦东新区", district: "洋泾街道", c_type: "普通")
Community.create(id: 124, code: 21208, street: "浦东新区", district: "周家渡街道", c_type: "普通")
Community.create(id: 125, code: 21209, street: "浦东新区", district: "浦兴路街道", c_type: "普通")
Community.create(id: 126, code: 21210, street: "浦东新区", district: "东明街道", c_type: "普通")
Community.create(id: 127, code: 21211, street: "浦东新区", district: "花木街道", c_type: "普通")
Community.create(id: 128, code: 21212, street: "浦东新区", district: "三林镇", c_type: "普通")
Community.create(id: 129, code: 21213, street: "浦东新区", district: "川沙新镇", c_type: "普通")
Community.create(id: 130, code: 21214, street: "浦东新区", district: "高桥镇", c_type: "普通")
Community.create(id: 131, code: 21215, street: "浦东新区", district: "北蔡镇", c_type: "普通")
Community.create(id: 132, code: 21216, street: "浦东新区", district: "张江镇", c_type: "普通")
Community.create(id: 133, code: 21217, street: "浦东新区", district: "曹路镇", c_type: "普通")
Community.create(id: 134, code: 21218, street: "浦东新区", district: "唐镇", c_type: "普通")
Community.create(id: 135, code: 21219, street: "浦东新区", district: "合庆镇", c_type: "普通")
Community.create(id: 136, code: 21220, street: "浦东新区", district: "金桥镇", c_type: "普通")
Community.create(id: 137, code: 21221, street: "浦东新区", district: "高东镇", c_type: "普通")
Community.create(id: 138, code: 21222, street: "浦东新区", district: "高行镇", c_type: "普通")
Community.create(id: 139, code: 21223, street: "浦东新区", district: "惠南镇", c_type: "普通")
Community.create(id: 140, code: 21224, street: "浦东新区", district: "周浦镇", c_type: "普通")
Community.create(id: 141, code: 21225, street: "浦东新区", district: "新场镇", c_type: "普通")
Community.create(id: 142, code: 21226, street: "浦东新区", district: "大团镇", c_type: "普通")
Community.create(id: 143, code: 21227, street: "浦东新区", district: "芦潮港镇", c_type: "普通")
Community.create(id: 144, code: 21228, street: "浦东新区", district: "康桥镇", c_type: "普通")
Community.create(id: 145, code: 21229, street: "浦东新区", district: "航头镇", c_type: "普通")
Community.create(id: 146, code: 21230, street: "浦东新区", district: "六灶镇", c_type: "普通")
Community.create(id: 147, code: 21231, street: "浦东新区", district: "祝桥镇", c_type: "普通")
Community.create(id: 148, code: 21232, street: "浦东新区", district: "泥城镇", c_type: "普通")
Community.create(id: 149, code: 21233, street: "浦东新区", district: "宣桥镇", c_type: "普通")
Community.create(id: 150, code: 21234, street: "浦东新区", district: "书院镇", c_type: "普通")
Community.create(id: 151, code: 21235, street: "浦东新区", district: "万祥镇镇", c_type: "普通")
Community.create(id: 152, code: 21236, street: "浦东新区", district: "老港镇", c_type: "普通")
Community.create(id: 153, code: 21237, street: "浦东新区", district: "芦潮港农场", c_type: "普通")
Community.create(id: 154, code: 21238, street: "浦东新区", district: "东海农场", c_type: "普通")
Community.create(id: 155, code: 21239, street: "浦东新区", district: "朝阳农场", c_type: "普通")
Community.create(id: 156, code: 21240, street: "浦东新区", district: "申港街道", c_type: "普通")
Community.create(id: 157, code: 21241, street: "浦东新区", district: "老港镇", c_type: "普通")
Community.create(id: 158, code: 21300, street: "金山", district: "石化街道", c_type: "普通")
Community.create(id: 159, code: 21301, street: "金山", district: "朱泾镇", c_type: "普通")
Community.create(id: 160, code: 21302, street: "金山", district: "吕巷镇", c_type: "普通")
Community.create(id: 161, code: 21303, street: "金山", district: "廊下镇", c_type: "普通")
Community.create(id: 162, code: 21304, street: "金山", district: "金山卫镇", c_type: "普通")
Community.create(id: 163, code: 21305, street: "金山", district: "枫泾镇", c_type: "普通")
Community.create(id: 164, code: 21306, street: "金山", district: "漕泾镇", c_type: "普通")
Community.create(id: 165, code: 21307, street: "金山", district: "山阳镇", c_type: "普通")
Community.create(id: 166, code: 21308, street: "金山", district: "亭林镇", c_type: "普通")
Community.create(id: 167, code: 21309, street: "金山", district: "张堰镇", c_type: "普通")
Community.create(id: 168, code: 21310, street: "金山", district: "金山工业区", c_type: "普通")
Community.create(id: 169, code: 21400, street: "松江", district: "岳阳街道", c_type: "普通")
Community.create(id: 170, code: 21401, street: "松江", district: "永丰街道", c_type: "普通")
Community.create(id: 171, code: 21402, street: "松江", district: "方松街道", c_type: "普通")
Community.create(id: 172, code: 21403, street: "松江", district: "中山街道", c_type: "普通")
Community.create(id: 173, code: 21404, street: "松江", district: "泗泾镇", c_type: "普通")
Community.create(id: 174, code: 21405, street: "松江", district: "佘山镇", c_type: "普通")
Community.create(id: 175, code: 21406, street: "松江", district: "洞泾镇", c_type: "普通")
Community.create(id: 176, code: 21407, street: "松江", district: "车墩镇", c_type: "普通")
Community.create(id: 177, code: 21408, street: "松江", district: "新桥镇", c_type: "普通")
Community.create(id: 178, code: 21409, street: "松江", district: "九亭镇", c_type: "普通")
Community.create(id: 179, code: 21410, street: "松江", district: "泖港镇", c_type: "普通")
Community.create(id: 180, code: 21411, street: "松江", district: "石湖荡镇", c_type: "普通")
Community.create(id: 181, code: 21412, street: "松江", district: "新浜镇", c_type: "普通")
Community.create(id: 182, code: 21413, street: "松江", district: "叶榭镇", c_type: "普通")
Community.create(id: 183, code: 21414, street: "松江", district: "小昆山镇", c_type: "普通")
Community.create(id: 184, code: 21500, street: "青浦", district: "夏阳街道", c_type: "普通")
Community.create(id: 185, code: 21501, street: "青浦", district: "盈浦街道", c_type: "普通")
Community.create(id: 186, code: 21502, street: "青浦", district: "香花桥街道", c_type: "普通")
Community.create(id: 187, code: 21503, street: "青浦", district: "朱家角街道", c_type: "普通")
Community.create(id: 188, code: 21504, street: "青浦", district: "练塘镇", c_type: "普通")
Community.create(id: 189, code: 21505, street: "青浦", district: "金泽镇", c_type: "普通")
Community.create(id: 190, code: 21506, street: "青浦", district: "赵巷镇", c_type: "普通")
Community.create(id: 191, code: 21507, street: "青浦", district: "徐泾镇", c_type: "普通")
Community.create(id: 192, code: 21508, street: "青浦", district: "华新镇", c_type: "普通")
Community.create(id: 193, code: 21509, street: "青浦", district: "重固镇", c_type: "普通")
Community.create(id: 194, code: 21510, street: "青浦", district: "白鹤镇", c_type: "普通")
Community.create(id: 195, code: 21600, street: "奉贤", district: "南桥镇", c_type: "普通")
Community.create(id: 196, code: 21601, street: "奉贤", district: "奉城镇", c_type: "普通")
Community.create(id: 197, code: 21602, street: "奉贤", district: "四团镇", c_type: "普通")
Community.create(id: 198, code: 21603, street: "奉贤", district: "金汇镇", c_type: "普通")
Community.create(id: 199, code: 21604, street: "奉贤", district: "青村镇", c_type: "普通")
Community.create(id: 200, code: 21605, street: "奉贤", district: "庄行镇", c_type: "普通")
Community.create(id: 201, code: 21606, street: "奉贤", district: "柘林镇", c_type: "普通")
Community.create(id: 202, code: 21607, street: "奉贤", district: "海湾镇", c_type: "普通")
Community.create(id: 203, code: 21700, street: "崇明", district: "城桥镇", c_type: "普通")
Community.create(id: 204, code: 21701, street: "崇明", district: "堡镇", c_type: "普通")
Community.create(id: 205, code: 21702, street: "崇明", district: "新河镇", c_type: "普通")
Community.create(id: 206, code: 21703, street: "崇明", district: "庙镇", c_type: "普通")
Community.create(id: 207, code: 21704, street: "崇明", district: "竖新镇", c_type: "普通")
Community.create(id: 208, code: 21705, street: "崇明", district: "向化镇", c_type: "普通")
Community.create(id: 209, code: 21706, street: "崇明", district: "三星镇", c_type: "普通")
Community.create(id: 210, code: 21707, street: "崇明", district: "港沿镇", c_type: "普通")
Community.create(id: 211, code: 21708, street: "崇明", district: "中兴镇", c_type: "普通")
Community.create(id: 212, code: 21709, street: "崇明", district: "陈家镇", c_type: "普通")
Community.create(id: 213, code: 21710, street: "崇明", district: "绿华镇", c_type: "普通")
Community.create(id: 214, code: 21711, street: "崇明", district: "港西镇", c_type: "普通")
Community.create(id: 215, code: 21712, street: "崇明", district: "建设镇", c_type: "普通")
Community.create(id: 216, code: 21713, street: "崇明", district: "新村乡", c_type: "普通")
Community.create(id: 217, code: 21714, street: "崇明", district: "长兴镇", c_type: "普通")
Community.create(id: 218, code: 21715, street: "崇明", district: "横沙乡", c_type: "普通")
Community.create(id: 219, code: 21716, street: "崇明", district: "东平镇", c_type: "普通")
Community.create(id: 220, code: 21717, street: "崇明", district: "新海镇", c_type: "普通")
